output = "./internal/persistence/database_helpers/mysql/assets/mysqlmodel"
pkgname = "mysqlmodel"

[[aliases.tables]]
name          = "report_ran"
up_plural     = "ReportRuns"
up_singular   = "ReportRan"
down_plural   = "ReportRuns"
down_singular = "ReportRan"

[mysql]
dbname  = "platform_engineer"
host    = "localhost"
port    = 3337
user    = "demby"
pass    = "secret"
sslmode = "false"