// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysqlmodel

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CapturePageSets", testCapturePageSetsUpsert)

	t.Run("CapturePages", testCapturePagesUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("CategoryTypes", testCategoryTypesUpsert)

	t.Run("Organizations", testOrganizationsUpsert)

	t.Run("OrganizationTypes", testOrganizationTypesUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
