// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysqlmodel

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOrganizationTypes(t *testing.T) {
	t.Parallel()

	query := OrganizationTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOrganizationTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrganizationTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OrganizationTypes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrganizationTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrganizationTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrganizationTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OrganizationTypeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OrganizationType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OrganizationTypeExists to return true, but got false.")
	}
}

func testOrganizationTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	organizationTypeFound, err := FindOrganizationType(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if organizationTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOrganizationTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OrganizationTypes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOrganizationTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OrganizationTypes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOrganizationTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	organizationTypeOne := &OrganizationType{}
	organizationTypeTwo := &OrganizationType{}
	if err = randomize.Struct(seed, organizationTypeOne, organizationTypeDBTypes, false, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}
	if err = randomize.Struct(seed, organizationTypeTwo, organizationTypeDBTypes, false, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = organizationTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = organizationTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrganizationTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOrganizationTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	organizationTypeOne := &OrganizationType{}
	organizationTypeTwo := &OrganizationType{}
	if err = randomize.Struct(seed, organizationTypeOne, organizationTypeDBTypes, false, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}
	if err = randomize.Struct(seed, organizationTypeTwo, organizationTypeDBTypes, false, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = organizationTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = organizationTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func organizationTypeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func organizationTypeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrganizationType) error {
	*o = OrganizationType{}
	return nil
}

func testOrganizationTypesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &OrganizationType{}
	o := &OrganizationType{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrganizationType object: %s", err)
	}

	AddOrganizationTypeHook(boil.BeforeInsertHook, organizationTypeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	organizationTypeBeforeInsertHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.AfterInsertHook, organizationTypeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	organizationTypeAfterInsertHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.AfterSelectHook, organizationTypeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	organizationTypeAfterSelectHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.BeforeUpdateHook, organizationTypeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	organizationTypeBeforeUpdateHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.AfterUpdateHook, organizationTypeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	organizationTypeAfterUpdateHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.BeforeDeleteHook, organizationTypeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	organizationTypeBeforeDeleteHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.AfterDeleteHook, organizationTypeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	organizationTypeAfterDeleteHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.BeforeUpsertHook, organizationTypeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	organizationTypeBeforeUpsertHooks = []OrganizationTypeHook{}

	AddOrganizationTypeHook(boil.AfterUpsertHook, organizationTypeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	organizationTypeAfterUpsertHooks = []OrganizationTypeHook{}
}

func testOrganizationTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrganizationTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(organizationTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrganizationTypeToManyOrganizationTypeRefOrganizations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OrganizationType
	var b, c Organization

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, organizationDBTypes, false, organizationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, organizationDBTypes, false, organizationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.OrganizationTypeRefID = a.ID
	c.OrganizationTypeRefID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.OrganizationTypeRefOrganizations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.OrganizationTypeRefID == b.OrganizationTypeRefID {
			bFound = true
		}
		if v.OrganizationTypeRefID == c.OrganizationTypeRefID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := OrganizationTypeSlice{&a}
	if err = a.L.LoadOrganizationTypeRefOrganizations(ctx, tx, false, (*[]*OrganizationType)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.OrganizationTypeRefOrganizations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.OrganizationTypeRefOrganizations = nil
	if err = a.L.LoadOrganizationTypeRefOrganizations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.OrganizationTypeRefOrganizations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testOrganizationTypeToManyAddOpOrganizationTypeRefOrganizations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OrganizationType
	var b, c, d, e Organization

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, organizationTypeDBTypes, false, strmangle.SetComplement(organizationTypePrimaryKeyColumns, organizationTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Organization{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, organizationDBTypes, false, strmangle.SetComplement(organizationPrimaryKeyColumns, organizationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Organization{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddOrganizationTypeRefOrganizations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.OrganizationTypeRefID {
			t.Error("foreign key was wrong value", a.ID, first.OrganizationTypeRefID)
		}
		if a.ID != second.OrganizationTypeRefID {
			t.Error("foreign key was wrong value", a.ID, second.OrganizationTypeRefID)
		}

		if first.R.OrganizationTypeRef != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.OrganizationTypeRef != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.OrganizationTypeRefOrganizations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.OrganizationTypeRefOrganizations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.OrganizationTypeRefOrganizations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testOrganizationTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrganizationTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrganizationTypeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrganizationTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrganizationTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	organizationTypeDBTypes = map[string]string{`ID`: `int`, `CreatedBy`: `int`, `CreatedDate`: `timestamp`, `LastUpdated`: `timestamp`, `UpdatedBy`: `int`, `IsActive`: `int`, `Name`: `varchar`}
	_                       = bytes.MinRead
)

func testOrganizationTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(organizationTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(organizationTypeAllColumns) == len(organizationTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOrganizationTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(organizationTypeAllColumns) == len(organizationTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrganizationType{}
	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, organizationTypeDBTypes, true, organizationTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(organizationTypeAllColumns, organizationTypePrimaryKeyColumns) {
		fields = organizationTypeAllColumns
	} else {
		fields = strmangle.SetComplement(
			organizationTypeAllColumns,
			organizationTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OrganizationTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOrganizationTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(organizationTypeAllColumns) == len(organizationTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLOrganizationTypeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OrganizationType{}
	if err = randomize.Struct(seed, &o, organizationTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrganizationType: %s", err)
	}

	count, err := OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, organizationTypeDBTypes, false, organizationTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrganizationType struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrganizationType: %s", err)
	}

	count, err = OrganizationTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
